### ISSUE TITLE
incorrect test dataset gets downloaded

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-study-template#56]
If I do:

```sh
$ python tests/download_test_data.py ds000248
```

I get download for eeg_matching_pennies:

```sh
/home/mainak/anaconda2/envs/mne/lib/python3.6/site-packages/numba/decorators.py:146: RuntimeWarning: Caching is not available when the 'parallel' target is in use. Caching is now being disabled to allow execution to continue.
  warnings.warn(msg, RuntimeWarning)

----------------------
datalad installing "eeg_matchingpennies"
datalad get data "sub-05" for "eeg_matchingpennies"
```

@agramfort can you replicate?

**Comment by agramfort** [comment]
I see the same.

>

**Comment by sappelhoff** [comment]
actually, all datasets get downloaded. This might be an issue with the "optparser" ... In `run_tests.py` I use "argparse" instead of the mne opt parser --> I find it much easier to deal with for these simple cases 

also, argparse kind of replaced optparse (which the MNE optparse is a wrapper around?): https://stackoverflow.com/a/3217687/5201771

**Comment by hoechenberger** [comment]
I don't see this issue anymore
